# Generated by Django 3.1 on 2024-04-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_filmproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
