# Generated by Django 3.1 on 2024-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
