# Generated by Django 3.1 on 2024-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0003_filmproject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmproject',
            name='actor',
            field=models.TextField(default='accc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmproject',
            name='date',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmproject',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
