# Generated by Django 3.1 on 2024-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0004_auto_20240331_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmproject',
            name='category',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
