# Generated by Django 3.1 on 2024-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0005_filmproject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmproject',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
