# Generated by Django 5.0.3 on 2024-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0006_filmproject_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
