# Generated by Django 5.0.3 on 2024-04-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0008_register_rename_filmproject_addmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stars', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
