# Generated by Django 3.1 on 2024-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmprojectapp', '0002_auto_20240326_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmproject',
            name='img',
            field=models.ImageField(default='aabbcc', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
